Repository Lit-innosence/tus_yuurikai_system, pull requests merged in 2024-11, with the labels that each got.

#29 Fix/Backend api bugs
  migrations/2024-08-19-155341_create_auth/up.sql
  src/adapters/controller.rs
  src/adapters/httpmodels.rs
  src/adapters/repository.rs
  src/infrastructure/models.rs
  src/main.rs
  src/usecase/assignment_record.rs
  src/usecase/auth.rs
  tests/lockerregister.rs
Labels: bug

#34 Fix/Usersearch and auth process api bugs
  frontend/src/routes/admin/LockerSearch.tsx
  frontend/src/routes/locker/MailAuth.tsx
  frontend/src/routes/locker/Register.tsx
  frontend/src/routes/locker/RegisterConfirm.tsx
  src/adapters/controller.rs
  src/adapters/httpmodels.rs
  tests/availability.rs
  tests/lockerregister.rs
  tests/usersearch.rs
  tests/utils/router.rs
Labels: bug

#33 Feature/Frontend-circle-select
  frontend/src/App.tsx
  frontend/src/routes/admin/CircleSelect.tsx
  frontend/src/routes/circle/CircleSelect.tsx
  frontend/src/routes/component/Redirect.tsx
Labels: enhancement

#35 Feature/Frontend-circle-status
  frontend/src/App.tsx
  frontend/src/routes/circle/CircleRegister.tsx
Labels: enhancement

#36 Feat/Backend-locker-reset
  .env.sample
  src/adapters/controller.rs
  src/adapters/httpmodels.rs
  src/adapters/repository.rs
  src/main.rs
  src/usecase/locker.rs
  tests/lockerregister.rs
  tests/lockerreset.rs
  tests/utils/router.rs
Labels: enhancement, test

#39 Clean/backend-auth-process
  frontend/src/routes/locker/MailAuth.tsx
  frontend/src/routes/locker/Register.tsx
  frontend/src/routes/locker/RegisterConfirm.tsx
  migrations/2024-08-19-155341_create_auth/up.sql
  migrations/2024-11-15-094630_create_locker_auth_info/down.sql
  migrations/2024-11-15-094630_create_locker_auth_info/up.sql
  src/adapters/controller.rs
  src/adapters/controller/circle.rs
  src/adapters/controller/locker.rs
  src/adapters/httpmodels.rs
  src/adapters/repository.rs
  src/infrastructure/models.rs
  src/infrastructure/router.rs
  src/main.rs
  src/usecase/auth.rs
  tests/lockerregister.rs
  tests/lockerreset.rs
  tests/login.rs
  tests/utils/router.rs
  tests/utils/setup.rs
Labels: clean

#41 Feat/Add-token-gen-API
  migrations/2024-11-21-141439_create_circle_auth_info/down.sql
  migrations/2024-11-21-141439_create_circle_auth_info/up.sql
  src/adapters/controller.rs
  src/adapters/controller/circle.rs
  src/adapters/controller/locker.rs
  src/adapters/httpmodels.rs
  src/adapters/repository.rs
  src/domain.rs
  src/domain/circle.rs
  src/domain/student.rs
  src/infrastructure/models.rs
  src/infrastructure/router.rs
  src/main.rs
  src/usecase/auth.rs
  tests/lockerregister.rs
Labels: enhancement
