Repository Lit-innosence/tus_yuurikai_system, pull requests merged in 2025-01, with the labels that each got.

#45 Fix/Frontend-auth-loading
  frontend/src/routes/circle/UpdateAuth.tsx
Labels: clean

#46 Feature/Frontend-access-restriction
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/routes/admin/CircleAccessLimit.tsx
  frontend/src/routes/admin/CircleSelect.tsx
Labels: enhancement

#47 Feature/backend-circle-status
  src/adapters/controller.rs
  src/adapters/controller/circle.rs
  src/adapters/httpmodels.rs
  src/adapters/repository/registration.rs
  src/adapters/repository/representatives.rs
  src/main.rs
  src/usecase/organization.rs
  src/usecase/registration.rs
Labels: enhancement

#48 Fix/Frontend-circle-status
  frontend/src/routes/circle/Status.tsx
  src/adapters/controller/circle.rs
  src/adapters/httpmodels.rs
  src/infrastructure/models.rs
Labels: bug

#50 Feature/Frontend-admin-status
  frontend/src/App.tsx
  frontend/src/routes/admin/CircleAccessLimit.tsx
  frontend/src/routes/admin/CircleList.tsx
Labels: enhancement
