Repository Lit-innosence/tus_yuurikai_system, pull requests merged in 2025-04, with the labels that each got.

#79 一部戻るボタンの削除とフォーム内容の維持
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/CustomHeader.tsx
  frontend/src/recoil/CircleForm.ts
  frontend/src/recoil/LockerForm.ts
  frontend/src/routes/Login.tsx
  frontend/src/routes/Toppage.tsx
  frontend/src/routes/circle/Update.tsx
  frontend/src/routes/circle/UpdateConfirm.tsx
  frontend/src/routes/locker/Form.tsx
Labels: 🐞 bug, 🔍 frontend, 📦 enhancement

#80 軽微な修正
  frontend/src/App.tsx
  frontend/src/components/TimeRouter.tsx
  frontend/src/routes/circle/Timeout.tsx
  src/domain/student.rs
  src/main.rs
Labels: 🐞 bug, ✨ feature, ⚠️ security, 🔍 frontend, 🖥️ backend

#81 リリース v1.3.0
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/CustomHeader.tsx
  frontend/src/components/TimeRouter.tsx
  frontend/src/recoil/CircleForm.ts
  frontend/src/recoil/LockerForm.ts
  frontend/src/routes/Login.tsx
  frontend/src/routes/Toppage.tsx
  frontend/src/routes/circle/Timeout.tsx
  frontend/src/routes/circle/Update.tsx
  frontend/src/routes/circle/UpdateConfirm.tsx
  frontend/src/routes/locker/Form.tsx
  src/domain/student.rs
  src/main.rs
Labels: minor

#83 App.tsxの修正と故障したロッカーの登録
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/components/TimeRouter.tsx
  frontend/src/routes/locker/ImportantConfirm.tsx
  frontend/src/routes/locker/Terms.tsx
  lockerdata.csv
Labels: 🐞 bug, 🔍 frontend

#84 データベースに関する同期処理のオフロード
  Cargo.lock
  Cargo.toml
  src/adapters/controller/locker.rs
  src/adapters/repository.rs
  src/adapters/repository/admin.rs
  src/adapters/repository/assignment_record.rs
  src/adapters/repository/auth.rs
  src/adapters/repository/circle_auth_info.rs
  src/adapters/repository/locker.rs
  src/adapters/repository/locker_auth_info.rs
  src/adapters/repository/organization.rs
  src/adapters/repository/registration.rs
  src/adapters/repository/representatives.rs
  src/adapters/repository/student.rs
  src/adapters/repository/student_pair.rs
  src/adapters/repository/time.rs
  src/domain/assignment.rs
  src/domain/student_pair.rs
  src/infrastructure/router.rs
  src/usecase/admin.rs
  src/usecase/assignment_record.rs
  src/usecase/auth.rs
  src/usecase/locker.rs
  src/usecase/organization.rs
  src/usecase/registration.rs
  src/usecase/representatives.rs
  src/usecase/student.rs
  src/usecase/student_pair.rs
  src/usecase/time.rs
  tests/availability.rs
  tests/lockerregister.rs
  tests/lockerreset.rs
  tests/login.rs
  tests/usersearch.rs
  tests/utils/router.rs
  tests/utils/setup.rs
Labels: ⚠️ security, 🖥️ backend, 📦 enhancement

#86 コード品質の向上
  src/adapters/controller/circle.rs
  src/adapters/controller/locker.rs
  src/infrastructure/router.rs
  src/main.rs
  src/usecase/admin.rs
  src/usecase/auth.rs
  src/usecase/locker.rs
  src/usecase/organization.rs
  src/usecase/registration.rs
  src/usecase/representatives.rs
  src/usecase/student.rs
  src/usecase/student_pair.rs
  src/usecase/time.rs
  src/utils/jwt.rs
Labels: 🛠️ refactor, 🖥️ backend, 📦 enhancement

#88 自前SMTPサーバーを用意するうえでの変更
  .env.sample
  src/usecase/auth.rs
Labels: 🖥️ backend, 📦 enhancement

#87 リリース v2.0.0
  .env.sample
  Cargo.lock
  Cargo.toml
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/components/TimeRouter.tsx
  frontend/src/routes/locker/ImportantConfirm.tsx
  frontend/src/routes/locker/Terms.tsx
  lockerdata.csv
  src/adapters/controller/circle.rs
  src/adapters/controller/locker.rs
  src/adapters/repository.rs
  src/adapters/repository/admin.rs
  src/adapters/repository/assignment_record.rs
  src/adapters/repository/auth.rs
  src/adapters/repository/circle_auth_info.rs
  src/adapters/repository/locker.rs
  src/adapters/repository/locker_auth_info.rs
  src/adapters/repository/organization.rs
  src/adapters/repository/registration.rs
  src/adapters/repository/representatives.rs
  src/adapters/repository/student.rs
  src/adapters/repository/student_pair.rs
  src/adapters/repository/time.rs
  src/domain/assignment.rs
  src/domain/student_pair.rs
  src/infrastructure/router.rs
  src/main.rs
  src/usecase/admin.rs
  src/usecase/assignment_record.rs
  src/usecase/auth.rs
  src/usecase/locker.rs
  src/usecase/organization.rs
  src/usecase/registration.rs
  src/usecase/representatives.rs
  src/usecase/student.rs
  src/usecase/student_pair.rs
  src/usecase/time.rs
  src/utils/jwt.rs
  tests/availability.rs
  tests/lockerregister.rs
  tests/lockerreset.rs
  tests/login.rs
  tests/usersearch.rs
  tests/utils/router.rs
  tests/utils/setup.rs
Labels: major

#89 リリース v2.0.1
  src/usecase/auth.rs
Labels: patch

#90 リリース v.2.0.2
  frontend/src/routes/Toppage.tsx
  src/adapters/controller/locker.rs
  src/usecase/time.rs
Labels: patch

#91 fix: log
  Dockerfile
  src/usecase/auth.rs
Labels: patch

#92 同じ学生の登録防止
  src/adapters/controller/locker.rs
  src/main.rs
  src/usecase/student_pair.rs
Labels: 🐞 bug, ⚠️ security, 🖥️ backend, 📦 enhancement

#93 リリース v.2.1.0
  src/adapters/controller/locker.rs
  src/main.rs
  src/usecase/student_pair.rs
Labels: minor

#95 リリース v2.1.1
  frontend/src/routes/locker/Form.tsx
  src/adapters/controller/locker.rs
Labels: patch

#96 ローカル環境の整備とバグの修正、整合性の確保
  .env.sample
  frontend/src/routes/admin/CircleAccessLimit.tsx
  frontend/src/routes/locker/Form.tsx
  frontend/src/routes/locker/ImportantConfirm.tsx
  frontend/src/routes/locker/RegisterComp.tsx
  frontend/src/routes/locker/RegisterConfirm.tsx
  run.sh
  src/adapters/controller/circle.rs
  src/adapters/controller/locker.rs
  src/infrastructure/router.rs
  src/main.rs
  src/usecase/auth.rs
Labels: 🐞 bug, ✨ feature, 🛠️ refactor, 🔍 frontend, 🖥️ backend, 📦 enhancement

#97 リリース v2.2.0
  .env.sample
  frontend/src/routes/admin/CircleAccessLimit.tsx
  frontend/src/routes/locker/Form.tsx
  frontend/src/routes/locker/ImportantConfirm.tsx
  frontend/src/routes/locker/RegisterComp.tsx
  frontend/src/routes/locker/RegisterConfirm.tsx
  run.sh
  src/adapters/controller/circle.rs
  src/adapters/controller/locker.rs
  src/infrastructure/router.rs
  src/main.rs
  src/usecase/auth.rs
Labels: minor
